services:
  mongodb:
    image: mongo:6.0
    container_name: pet-store-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - pet-store-network

  pet-store1:
    build: ./pet_store
    container_name: pet-store1
    ports:
      - "5001:5001"
    expose:
      - 5001
    environment:
      - MONGO_URI=mongodb://mongodb:27017/
      - DB_NAME=pet_store1
      - PORT=5001
    depends_on:
      - mongodb
    volumes:
      - ./images:/app/images
    networks:
      - pet-store-network
    restart: on-failure

  pet-store2:
    build: ./pet_store
    container_name: pet-store2
    ports:
      - "5002:5001"
    expose:
      - 5001
    environment:
      - MONGO_URI=mongodb://mongodb:27017/
      - DB_NAME=pet_store2
      - PORT=5001
    depends_on:
      - mongodb
    volumes:
      - ./images:/app/images
    networks:
      - pet-store-network
    restart: on-failure

  pet-order1:
    build: ./pet_order
    container_name: pet-order1
    ports:
      - "5003:5003"
    expose:
      - 5003
    environment:
      - MONGO_URI=mongodb://mongodb:27017/
      - PORT=5003
      - PET_STORE1_URL=http://pet-store1:5001
      - PET_STORE2_URL=http://pet-store2:5001
    depends_on:
      - mongodb
      - pet-store1
      - pet-store2
    networks:
      - pet-store-network
    restart: on-failure

  pet-order2:
    build: ./pet_order
    container_name: pet-order2
    expose:
      - 5003
    environment:
      - MONGO_URI=mongodb://mongodb:27017/
      - PORT=5003
      - PET_STORE1_URL=http://pet-store1:5001
      - PET_STORE2_URL=http://pet-store2:5001
    depends_on:
      - mongodb
      - pet-store1
      - pet-store2
    networks:
      - pet-store-network
    restart: on-failure

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - pet-store1
      - pet-store2
      - pet-order1
      - pet-order2
    networks:
      - pet-store-network

networks:
  pet-store-network:
    driver: bridge

volumes:
  mongodb_data:
