services:
  mongodb:
    image: mongo:6.0
    container_name: pet-store-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - pet-store-network

  pet-store:
    build: .
    container_name: pet-store-app
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/
    depends_on:
      - mongodb
    volumes:
      - ./images:/app/images
    networks:
      - pet-store-network

networks:
  pet-store-network:
    driver: bridge

volumes:
  mongodb_data:

